apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-mgomes-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-mgomes-d
  template:
    metadata:
      labels:
        app: argocd-mgomes-d
    spec:
      containers:
        - name: argocd-mgomes-d
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
