apiVersion: v1
kind: Service
metadata:
  name: argocd-mgomes-d
spec:
  selector:
    app: argocd-mgomes-d
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
# argocd app create argocd-mgomes-d --repo https://github.com/mgomes-d/argocd-mgomes-d.git --path argocd-deploy --dest-server https://kubernetes.default.svc --dest-namespace dev
